// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	url "github.com/DarcoProgramador/url-shortener/internal/url"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: shortUrl
func (_m *Repository) GetUrl(shortUrl string) (string, error) {
	ret := _m.Called(shortUrl)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(shortUrl)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUrl provides a mock function with given fields: shortUrl, originalUrl
func (_m *Repository) SaveUrl(shortUrl string, originalUrl string) (*url.Url, error) {
	ret := _m.Called(shortUrl, originalUrl)

	var r0 *url.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*url.Url, error)); ok {
		return rf(shortUrl, originalUrl)
	}
	if rf, ok := ret.Get(0).(func(string, string) *url.Url); ok {
		r0 = rf(shortUrl, originalUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Url)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(shortUrl, originalUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
